#!/usr/bin/env bash
# Provider Fallback Filter — Local Test Harness
#
# Prerequisites:
#   - Ollama running locally (ollama serve) with qwen2.5:3b
#   - OPENROUTER_API_KEY set in environment
#   - Optionally OPENROUTER_BASE_URL (defaults to https://openrouter.ai/api/v1)
#   - Praxis built (cargo build -p praxis-proxy)
#
# Usage:
#   export OPENROUTER_API_KEY="sk-or-..."
#   ./filter/provider-fallback/test.sh

set -euo pipefail

PROXY_PORT=8070
OLLAMA_URL="http://127.0.0.1:11434"
OLLAMA_MODEL="qwen2.5:3b"
OPENROUTER_BASE="${OPENROUTER_BASE_URL:-https://openrouter.ai/api/v1}"
OPENROUTER_MODEL="qwen/qwen3-coder:free"

# ── Preflight Checks ─────────────────────────────────────────────

if [[ -z "${OPENROUTER_API_KEY:-}" ]]; then
    echo "ERROR: OPENROUTER_API_KEY is not set"
    echo "  export OPENROUTER_API_KEY=\"sk-or-...\""
    exit 1
fi

echo "==> Checking Ollama at ${OLLAMA_URL} ..."
if curl -sf "${OLLAMA_URL}/api/tags" > /dev/null 2>&1; then
    echo "    Ollama is running"

    # Check if model is available
    if curl -sf "${OLLAMA_URL}/api/tags" | grep -q "qwen2.5"; then
        echo "    Model ${OLLAMA_MODEL} is available"
    else
        echo "    Model ${OLLAMA_MODEL} not found — pulling it now ..."
        echo "    (this may take a while on first run)"
        ollama pull "${OLLAMA_MODEL}"
    fi
else
    echo "WARNING: Ollama is not running at ${OLLAMA_URL}"
    echo "  Start it with: ollama serve"
    echo "  The first target will fail and fallback to OpenRouter"
    echo ""
fi

echo "==> OPENROUTER_API_KEY is set (${#OPENROUTER_API_KEY} chars)"
echo "==> OpenRouter base URL: ${OPENROUTER_BASE}"
echo "==> OpenRouter model: ${OPENROUTER_MODEL}"
echo ""

# ── Generate Config ──────────────────────────────────────────────

CONFIG_FILE=$(mktemp /tmp/praxis-fallback-XXXXXX.yaml)
trap 'rm -f "${CONFIG_FILE}"' EXIT

cat > "${CONFIG_FILE}" << YAML
# Provider Fallback Test Config (generated by test.sh)

listeners:
  - name: ai
    address: "127.0.0.1:${PROXY_PORT}"
    filter_chains:
      - inference

filter_chains:
  - name: inference
    filters:
      - filter: provider_fallback
        max_body_bytes: 1048576
        circuit_breaker:
          consecutive_failures: 3
          recovery_window_ms: 30000
        targets:
          - url: "${OLLAMA_URL}/v1/chat/completions"
            model_override: "${OLLAMA_MODEL}"
            timeout_ms: 30000
          - url: "${OPENROUTER_BASE}/chat/completions"
            model_override: "${OPENROUTER_MODEL}"
            timeout_ms: 30000
            headers:
              Authorization: "Bearer ${OPENROUTER_API_KEY}"
YAML

echo "==> Generated config: ${CONFIG_FILE}"
echo ""
cat "${CONFIG_FILE}"
echo ""

# ── Build ────────────────────────────────────────────────────────

echo "==> Building praxis-proxy ..."
cargo build -p praxis-proxy 2>&1 | tail -1
echo ""

# ── Start Proxy ──────────────────────────────────────────────────

echo "==> Starting Praxis on 127.0.0.1:${PROXY_PORT} ..."
echo "    (Ctrl+C to stop)"
echo ""
echo "──────────────────────────────────────────────────────────────"
echo "  Test commands (run in another terminal):"
echo ""
echo "  # Basic chat completion (tries Ollama first, then OpenRouter):"
echo "  curl -s http://127.0.0.1:${PROXY_PORT}/v1/chat/completions \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"model\":\"any\",\"messages\":[{\"role\":\"user\",\"content\":\"Say hello in one sentence.\"}]}' | jq ."
echo ""
echo "  # With request ID for log correlation:"
echo "  curl -s http://127.0.0.1:${PROXY_PORT}/v1/chat/completions \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -H 'X-Request-Id: test-001' \\"
echo "    -d '{\"model\":\"any\",\"messages\":[{\"role\":\"user\",\"content\":\"What is 2+2?\"}]}' | jq ."
echo ""
echo "  # Force fallback (stop Ollama, then re-run curl):"
echo "  #   ollama stop"
echo "  #   <run curl again — should hit OpenRouter>"
echo "──────────────────────────────────────────────────────────────"
echo ""

RUST_LOG=info,praxis_provider_fallback=debug cargo run -p praxis-proxy -- -c "${CONFIG_FILE}"
